### ISSUE TITLE
fix: edit in preview not work

### ISSUE THREAD

**Issue by zapcannon87** [leancloud/ticket#110]
## 问题

在 preview 里编辑文本后，返回到上一级页面，此时文本框的文本显示是已经编辑后的文本，但是点击「提交回复」后，提交的文本并不是编辑后的文本。

[zulip 链接 >](https://zulip.leancloud.tk/#narrow/stream/15-tech-support/topic/ticket-edit-preview/near/1995380)

**Comment by leeyeh** [comment]
fixed via d7e57973185507a92ec884fd0e204bbbb37de439
