### ISSUE TITLE
用和控制台类似的方式把工单 UI 国际化

### ISSUE THREAD

**Issue by hjiang** [leancloud/ticket#115]

**Comment by weakish** [comment]
控制台用的是 react-i18next，它支持 hook、HOC、render prop、Trans，hook 是 React 16 开始才支持的，而工单的 React 版本还是 15，另外三种方式，试验的结果是碰到报错 `_react.default.createContext is not a function`，看起来 react-18next 用到了 React 15 不支持的 context API 特性。

我试验了下 airbnb 的 Polyglot 库，看起来是可用的，详见 #117

还有一个方案就是干脆换 zendesk 这样的第三方（[zulip](https://zulip.lcops.cn/#narrow/stream/28-api/topic/livequery/near/1064842)）。好处是不需要国际化工单了（我看了下，[zendesk 的文档说界面语言也是支持中文的][zendesk]），另外也能避免故障的时候发不了工单的尴尬情况。当然接 zendesk 也需要一些和现有系统的适配工作（oauth、各个渠道的通知等）。

[zendesk]: https://support.zendesk.com/hc/en-us/articles/203761906
