### ISSUE TITLE
重新梳理和改进工单统计页面

### ISSUE THREAD

**Issue by sdjdd** [leancloud/ticket#142]
[wiki 链接](https://leancloud.atlassian.net/wiki/spaces/kb/pages/1972043794/2021#%E4%B8%80%E3%80%81%E9%87%8D%E6%96%B0%E6%A2%B3%E7%90%86%E5%92%8C%E6%94%B9%E8%BF%9B%E5%B7%A5%E5%8D%95%E7%BB%9F%E8%AE%A1%E9%A1%B5%E9%9D%A2)

> 需要确认一下：平均首次响应时长是否按照周期内新增工单统计，平均响应时长是否按照活跃工单统计。

已确认符合描述

> 活跃工单数（分类）下面所有分类的统计数量累加与总览中活跃工单总数不一致。

各活跃工单数的统计是根据以天为单位生成的统计数据聚合而成，每天的活跃工单会有交集。总览中的活跃工单数根据工单的 objectId 做了去重，所以总数对应不上。由于每天的统计数据仅保存了客服、分类、用户对应的工单数量，没法在聚合时去重，所以这块需要重新设计。

> 有的客服名字是 undefined

这个是因为 StatsTicket 表里有下面这样的骚数据：
```json
{
  "ticketId": "5ffe535b5f9f6d0246a54fc9",
  "firstReplyTime": null
}
```
正常的应该是这样：
```json
{
  "ticketId": "5ffd89dc17e9de6b39a54f18",
  "userId": "5757b7bc6be3ff00692f5f2b",
  "firstReplyTime": 4461927
}
```
可以修改下生成数据的逻辑，或者统计时过滤掉非法数据。

1、2 条需要修改统计的逻辑，或者增加一个表、列存放新格式的统计数据。 @weakish @SXiaoXu 听下两位的想法 👀

**Comment by SXiaoXu** [comment]
## 1. 平均首次响应时长是否按照周期内新增工单统计，平均响应时长是否按照活跃工单统计。

第一个问题，期望实现的是，平均首次响应按照本周（本月）新增工单的统计，不应该按照活跃工单计算，这样可能把历史工单在几周内都重复计算「平均首次响应」时间。

「平均响应时长」可以维持原样按照活跃工单计算。

## 2.活跃工单数（分类）下面所有分类的统计数量累加与总览中活跃工单总数不一致。

> 各活跃工单数的统计是根据以天为单位生成的统计数据聚合而成，每天的活跃工单会有交集。

感觉可以算是一个 BUG 吧，如果这样的话，有一个「短信」分类的工单连续活跃了 7 天，就会被统计 7 次。可能最后的统计数据就没有参考价值了。应该是要改的，具体怎么修改表结构，也可以听听看陈伟有没有什么建议  @sdjcw

**Comment by sdjdd** [comment]
更正一下：平均首次响应时长确实是按照周期内新增工单统计的，实现方式是获取周期内活跃工单，根据活跃工单的 createdAt 过滤出新增工单，再进行统计。
