### ISSUE TITLE
markdown 编辑器粘贴上传图片优化

### ISSUE THREAD

**Issue by leeyeh** [leancloud/ticket#152]
上传文件的时候应该有一个 loading 的状态展示，插入的位置应该在当前光标位置。

**Comment by sdjdd** [comment]
还是引入一个富文本编辑器吧，这个轮子太大拉。

**Comment by leeyeh** [comment]
除了这两点我觉得现在的编辑体验也没啥问题啊，有的话可以详细说说。富文本编辑器是大坑，还是 markdown 香。

**Comment by sdjdd** [comment]
我感觉要弄成 github 这样还是挺麻烦的。

**Comment by sdjdd** [comment]
这个之前重构成 hook + 函数组件的时候顺手改了。
