### ISSUE TITLE
工单进不去而且全部都没有了！！！但是我还能收到回复。。。卧槽！！！！！

### ISSUE THREAD

**Issue by SeasonLeee** [leancloud/ticket#156]
什么情况？？？HELP!!!!!! PLEASE!!!!!!!

**Comment by SeasonLeee** [comment]
![image](https://user-images.githubusercontent.com/13610283/105826038-455bb480-5ffb-11eb-8571-1f6e9ce7d41b.png)

https://leanticket.cn/tickets/37247

![image](https://user-images.githubusercontent.com/13610283/105826109-56a4c100-5ffb-11eb-92c3-51346d1a86c1.png)

**Comment by SXiaoXu** [comment]
请稍等，工单的问题我们正在处理。

**Comment by SeasonLeee** [comment]
啊你是那个人吧！！！！😭😭😭😭😭 救命。。。谢谢😭😭😭😭😭😭

**Comment by SXiaoXu** [comment]
我是工单中回复您的客服，我们的工程师正在解决工单打不开的问题，还请稍等。

**Comment by SeasonLeee** [comment]
你不仅仅是客服吧。。。。你不是开发了那些demo那些东西吗？还有在这里你可以不用“您”了，，，谢谢啦哈哈哈

**Comment by SXiaoXu** [comment]
关于工单中的问题，需要加一行代码：`PushService.setDefaultPushCallback(this, MainActivity.class);`

我刚测试是可以收到在线推送的：
![image](https://user-images.githubusercontent.com/11917002/105828734-71c50000-5ffe-11eb-8a82-8015577a3b17.png)

**Comment by SeasonLeee** [comment]
好的，谢谢！

那个还有这个问题，

这个
```
MainActivity.class 
```
指的是哪一个啊？是要Activity才行吗？

还是说指的是Application的class?

**Comment by SXiaoXu** [comment]
是指 Android 自动生成的  FlutterActivity，默认是 MainActivity。在 android 目录下可以找到。
