### ISSUE TITLE
用户工单已读功能

### ISSUE THREAD

**Issue by leeyeh** [leancloud/ticket#164]
需求类似 GitHub 未读通知标记的功能，包括了获取当前登录用户创建的工单是否有有新进展（从而显示小红点），在列表页标记出有新进展的工单。

在实现上一种简单的方式是在 Ticket 表中维护一个 unreadCount 的字段。当有新的进展时自动 increment 该字段。当用户进入工单详情页时手动将该字段置 0。其中「新的进展」包含了：

- 客服回复了工单（当前用户自己回复的不算）。
- 工单被关闭 / 重新打开（用户自己操作的不算）。

小红点可以通过在构造 Ticket 的查询时加上 `where unreadCount  > 0` 的条件后看有没有符合的结果来判断。

设计成「未读数与 Ticket 一对一关联」的好处是简单、直观，缺点是只能记录工单创建者的未读数，如果启用了「组织」功能，一个工单是由「组织」创建的，组织下的所有人都能访问的情况下，这个模型就不适用了。好在当前的需求并不需要考虑这种复杂的情况，我们可以简单对组织身份创建的工单跳过已读的功能。

在这个设计下，绝大部分都是 hook / function 内部以及客户端逻辑的改动，API 要做的改动不大：

- 提供一个「标记所有工单为已读」的新云函数，将当前登录用户创建的所有工单标批量记为已读。

**Comment by sdjdd** [comment]
组织下的工单，某个成员看过后清除 unreadCount 也没啥问题吧。

**Comment by weakish** [comment]
> 当有新的进展时自动 increment 该字段。当用户进入工单详情页时手动将该字段置 0

感觉用户通常不会关心某个工单下面具体多了几条回复，或者说，未读数应该是他发的工单中有几条有新进展，而不是发的工单中有几条新回复（打开、关闭视为回复），这种情况下，不考虑组织的话，这个字段可以是一个 bool 字段。

然后这个字段用 Set 或 Object 就能记录为组织中每个成员分别记录。

**Comment by sdjdd** [comment]
不用为组织成员分别记录吧，那样的话就是用户层面的通知了。

**Comment by leeyeh** [comment]
boolean 是可以我也想过，不过 number 的话能实现「几条未读」的功能，前者能实现的功能后者都能实现，只是可能理解起来会稍微复杂一点。

Set 或 Object 的话确实能实现每个成员单独记录，但这个可能就不适合直接 embed 到 Ticket 表里了，外加一个中间表的复杂度也会上升（而且似乎与 Notification 功能有些重叠？）。现在也没有非常明确的需求，还是按照简单的来吧。

**Comment by sdjdd** [comment]
> 提供一个「标记所有工单为已读」的新云函数，将当前登录用户创建的所有工单标批量记为已读。

只是将当前用户创建的工单标记为已读，无法批量标记用户所属的组织的工单，这样用户标记完后发现还有红点会不会觉得很奇怪？

**Comment by leeyeh** [comment]
所以才想说这个功能完全不考虑组织身份创建的工单。
