### ISSUE TITLE
客服页面的筛选里增加「无人负责」项目

### ISSUE THREAD

**Issue by leeyeh** [leancloud/ticket#187]
如果是认领模式的话，客服页面的筛选里，「无人负责」会是一个比较常用的项目，可以在「Assigned」那里加一下这个，放在「All」上面。

_Originally posted by @weakish in https://github.com/leancloud/ticket/pull/184#issuecomment-773152895_

**Comment by sdjdd** [comment]
认领模式目前从系统不分配客服改为创建一个接收所有工单的客服账号，值班客服从这个账号认领。
