### ISSUE TITLE
FAQs vs faqs

### ISSUE THREAD

**Issue by sdjdd** [leancloud/ticket#264]
创建分类时设置的是 `faqs` : https://github.com/leancloud/ticket/blob/6b99d670fcb1c4b25f484f18e1595f625147e67c/modules/Settings/Category.js#L96-L102

但在创建工单的页面显示的 FAQ 用的却是 `FAQs` : https://github.com/leancloud/ticket/blob/6b99d670fcb1c4b25f484f18e1595f625147e67c/modules/NewTicket.js#L157-L166

我不知道最先使用的是哪个，但 ticket 应用为【数据存储】分类设置了 `FAQs`。@soasurs 前几天添加 lean-cli 分类时系统自动为 `faqs` 设置了一个空数组，导致目前 ticket 应用的 Category Class 中既有 `FAQs` 也有 `faqs` 。

还是统一使用一个罢。

**Comment by leeyeh** [comment]
应该用 `FAQs`，是我在创建分类时写错了，我来改一下吧。

**Comment by leeyeh** [comment]
要是限制了「没有人能 add_fields」就能在开发阶段就看到这个问题了。
