### ISSUE TITLE
数据库中没有_Role的值

### ISSUE THREAD

**Issue by Angry-Chick** [leancloud/ticket#32]
进入工单界面提交工单刷新页面无法显示创建的工单，报错如下
Cannot read property 'getUsers' of undefined
源代码中报的错误是
return role.getUsers().query().ascending('username').find();

**Comment by sdjcw** [comment]
在工单系统第一个用户注册时，会创建两个 role 记录（代码 https://github.com/leancloud/ticket/blob/master/api/User.js#L46-L49）。

如果 _Role 表没有这些记录，建议删除掉 _User 表所有记录，并且重启应用，然后尝试注册第一个应用看看是否 role 记录能正常生成。如果不能，请反馈给我们。

**Comment by lanstonpeng** [comment]
我们已经删除掉_User中所有的数据，但是新注册的第一个用户依然没有在_Role中有数据，没法添加分类，也就没法添加工单了

**Comment by sdjcw** [comment]
你好，代码 https://github.com/leancloud/ticket/blob/master/api/User.js#L8 这个方法会在应用启动后 3 秒执行，并输出一行日志：「新应用启动，注册的第一个用户将成为管理员。」当看到这句话时，进行用户注册就可以了。

而且需要注意删掉所有用户之后，应用需要从重新启动下，也许是这一步忘记了。

如果实在没有，就在项目目录下创建一个 js 文件，比如 `initUser.js` ，内容如下：

```
const AV = require('leanengine')

AV.init({
  appId: process.env.LEANCLOUD_APP_ID,
  appKey: process.env.LEANCLOUD_APP_KEY,
  masterKey: process.env.LEANCLOUD_APP_MASTER_KEY
})
AV.Cloud.useMasterKey()

const addRole = (name, initUser) => {
  const roleAcl = new AV.ACL()
  roleAcl.setPublicReadAccess(true)
  roleAcl.setRoleWriteAccess(name, true)
  const role = new AV.Role(name, roleAcl)
  role.getUsers().add(initUser)
  return role.save()
}

const user = new AV.User()
user.setUsername('admin') // 这里是管理员的用户名
user.setPassword('123@abc') // 这里是管理员的密码
user.signUp()
  .then((user) => {
    return Promise.all([
      addRole('admin', user),
      addRole('customerService', user)
    ])
  })
```
然后在项目根目录执行：

```
$(lean env)
node initUser.js
```
如果没有任何错误信息输出，应该就能在 `_User` 表和 `_Role` 表看到相关信息了。
