### ISSUE TITLE
新版中添加企业微信支持

### ISSUE THREAD

**Issue by sdjdd** [leancloud/ticket#404]
企业微信的通知还是有人在用的，需要在新版中重新实现。

不过看旧版里用的 wechat-enterprise 这个库只支持 express，且已经 6 年没更新了，需要重新研究下咋实现。

**Comment by sayue2019** [comment]
还没实现啊

**Comment by sdjdd** [comment]
@sayue2019 这项工作的优先级较低，暂时还没有排期。

**Comment by sdjdd** [comment]
不再支持企业微信。
