### ISSUE TITLE
如果用户提交的工单内容太长（日志太多行），输入框是否可以加个提示「可以用附件上传日志」

### ISSUE THREAD

**Issue by SXiaoXu** [leancloud/ticket#408]
例如[工单](https://www.leanticket.cn/tickets/38401) ，每一次回复用户问题都要滑到底部，日志太长了。这类工单之前也遇到过几次。

**Comment by leeyeh** [comment]
几个优化的方法吧，slack 与 github 其实已经做得很好了，一是显示过长截断，而是粘贴文本超长自动转附件，三是回复过多中间隐藏。

可以先从 2

**Comment by sdjdd** [comment]
如果单独回复一长串日志，可以转成附件。但其中经常会夹杂着一些其他回复内容。
先实现 1 吧。

**Comment by weakish** [comment]
> 每一次回复用户问题都要滑到底部

按一下 End 键就到底部了

**Comment by leeyeh** [comment]
可以用 overflow:auto 来隐藏，那样能搜到。
