### ISSUE TITLE
最近工单的标题过长时会导致布局错乱

### ISSUE THREAD

**Issue by sdjdd** [leancloud/ticket#436]
![image](https://user-images.githubusercontent.com/33412425/142556820-20b81b7b-df9f-4710-b14c-6d3454cd9d7e.png)

**Comment by sdjdd** [comment]
一个练习 Flex 的机会 :wise:

**Comment by lywTYH** [comment]
不如让标题再短点

**Comment by sdjdd** [comment]
还是我来吧 :dh-sigh:
