### ISSUE TITLE
客服回复时，应该可以选择是否改变工单状态

### ISSUE THREAD

**Issue by hjiang** [leancloud/ticket#46]
现在客服回复后会自动改为「等待用户回复」，很多时候是错误的。在客服回复的时候应该有两个按钮一个是「提交并等待客户回复」，另一个是「提交并保持工单状态」。

**Comment by SXiaoXu** [comment]
其实现在客服提交回复以后，可以再点击一次「稍后回复」按钮，工单就保持在「等待客服回复状态」了。是否能满足需求？

**Comment by hjiang** [comment]
应该可以。
