### ISSUE TITLE
新的工单统计

### ISSUE THREAD

**Issue by lywTYH** [leancloud/ticket#484]
**工单统计 TicketStats**

用于统计工单信息，以工单为索引。看成工单的补充与工单为 1 对 1 的关系

1. 回复相关的统计
    * 首次回复时间  
    * 总回复次数（用户+客服对外）// 不包含内部回复
    * 用户回复次数  
    * 对外客服回复次数 （不计算是不是负责的客服）
    * 对内客服回复次数
    * 对外客服工作日回复次数
    * 对外客服平均回复时间 
    * 对外客服工作日平均回复时间 
2. 流转次数 
3. 关闭时间 

**时间 - 分类**
**时间 - 客服** 

以时间 - 客服为索引进行统计 客服的相关行为

工单创建数 ？
1. 回复相关的统计
      * 客服回复数 
      * 平均回复时间 
      * 工作日回复数
      * 工作日平均回复时间 
      * 对内回复数
2. 关单数
3. 激活工单数
4. 流转数
     * 内部流转数 从内部组其他负责人流转
     * 外部流转  从外部组其他负责人流转    
5. 及时数 / 及时率
 ？？
及时率 ：及时数/ 回复数

工单重新打开后，此工单还是否计入 关单数或者等待回复 

即刻状态单独建立新表
 * 等待回复  

权限都是仅 master 能读写

**Comment by lywTYH** [comment]
responseDetails 格式

```json
{
  type: 'reply' | 'action';
  action?: LogAction;
  internal?: boolean;
  authorId: string;
  responseTime: number;
  askDate: Date; // 用来判断回复对应提问的日期
  responseDate: Date;
}[];
```

**Comment by lywTYH** [comment]
相关表结构

 [TicketDailyStats](https://console.leancloud.cn/apps/02AXSPNhJaEqgBfHftLpIsj2-gzGzoHsz/storage/data/TicketDailyStats)

 [TicketStats](https://console.leancloud.cn/apps/02AXSPNhJaEqgBfHftLpIsj2-gzGzoHsz/storage/data/TicketStats)

**Comment by lywTYH** [comment]
TicketStats

|  字段   | 类型  | 含义 
|  ----  | ----  |----  |
| firstReplyTime  | number |首次回复时间|
| allReplyCount  | number | 总回复次数 
| userReplyCount  | number | 用户回复次数
| replyCount  | number | 客服回复次数
| replyInternalCount | number| 客服对内回复次数
| weekdaysReplyCount| number| 客服工作日回复次数
| averageReplyTime | number| 客服平均回复时间
| averageWeekdaysReplyTime | number| 客服工作日平均回复时间
| flowCount | number| 流转次数

**Comment by lywTYH** [comment]
参考

**freshDesk**
统计数据相对较少

<img width="1568" alt="Screen Shot 2022-01-06 at 14 37 01" src="https://user-images.githubusercontent.com/7405936/148340631-ac5f78b5-2f4f-4980-a5b8-48b8b268b7ae.png">
<img width="1486" alt="Screen Shot 2022-01-06 at 14 37 07" src="https://user-images.githubusercontent.com/7405936/148340652-0be9539c-0fb5-426e-9c8d-1760e54c5b07.png">

**zendesk** 

需要自建指标进行统计，展示也可以自己选择 （table or chart) (探索了下 没用好）
不过从文档中找出示例

![Explore-support-dashboard](https://user-images.githubusercontent.com/7405936/148340928-df3daa3f-9a28-4fc3-99a2-69bf6e0db7d4.png)

**Comment by sdjdd** [comment]
:respect:
