### ISSUE TITLE
更新 XSS 过滤策略

### ISSUE THREAD

**Issue by leeyeh** [leancloud/ticket#545]
当前使用的 xss 库的白名单有些过时，`kbd` 之类的 tag 都会被 escape，考虑换成基于黑名单的 dompurify。

**Comment by sdjdd** [comment]
干脆废弃 xxxHTML 的字段，全都在前端渲染 :wise:

**Comment by leeyeh** [comment]
因为是 v1 API + v1 Web 就不大改了。

**Comment by leeyeh** [comment]
等等你说的是全部前端渲染？这岂不是所有客户端都需要加一遍这个逻辑。

**Comment by sdjdd** [comment]
🤔
